SELECT 2chnavi_site.* FROM 2chnavi_site_articles INNER JOIN 2chnavi_site ON 2chnavi_site.id=2chnavi_site_articles.siteId WHERE 2chnavi_site_articles.title LIKE '%結果www%' AND 2chnavi_site.isGood=1 GROUP BY 2chnavi_site.id


INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'Oh!暇なのよ！？', 'http://ohhima.doorblog.jp/', NULL, 'http://ohhima.doorblog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'article-body-more', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'アイアイまとめん速報', 'http://blog.livedoor.jp/nandemojouhou/', 'アイドル情報などをいろいろまとめんおまとめしています！！', 'http://blog.livedoor.jp/nandemojouhou/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'article-body-more', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'パパッとニュース速報', 'http://papatto.blog.jp', NULL, 'http://papatto.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', '', 'monster2', 'article-body-innerar', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'にゃー速', 'http://blog.nyaasoku.com/', NULL, 'http://blog.nyaasoku.com/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'article-body-inner', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'なんＪチャレンジ｜2ch', 'http://blog.livedoor.jp/tangomin/', 'なんＪチャレンジ：スポーツ・サブカルチャー・ニュースをなんＪ民の反応と共にまとめます', 'http://blog.livedoor.jp/tangomin/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'article-body-single', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '芸能まとめ速報', 'http://geinoplus.blog.jp/', NULL, 'http://geinoplus.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'article-body-inner', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'マユゲット(2ちゃんまとめ）', 'http://mayugetto.blog.jp/', NULL, 'http://mayugetto.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'article-body-inner', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'ハローワーク速報', 'http://blog.livedoor.jp/rhiguchiblog/', NULL, 'http://blog.livedoor.jp/rhiguchiblog/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'article-body-inner', 't_h');

INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '２ちゃんを斬る！', 'http://kiru2ch.com/', '２ちゃんねるの持つ独特の面白さ、楽しさを余すことなくあなたに伝えたいブログ、２ちゃんを斬る！です。', 'http://kiru2ch.com/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'monster2', 'description', 't_h');

INSERT INTO `alligate_2`.`Tag` (`id`, `name`) VALUES ('12', 'gazo2');




INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '１００％　AKB！！　～AKB全部まとめました～', 'http://akb100per.blog.jp/', NULL, 'http://akb100per.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'あの人の噂　～芸能速報まとめ～', 'http://anohitonouwasa.blog.jp/', NULL, 'http://anohitonouwasa.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '今日の乃木坂。', 'http://kyounonogizaka.blog.jp/', NULL, 'http://kyounonogizaka.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'ももクロ速報ぉ', 'http://momosoku.blog.jp/', NULL, 'http://momosoku.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'ROMれ！ペンギン(AKB48まとめ)', 'http://www.akb48rompen.com/', 'AKB48関連のまとめブログです。 「ろむぺん(ロムペン)」とでも呼んでください。 9期以降のメンバーの記事が中心になると思います。 大場美奈・山内鈴蘭・市川美織の移籍に伴いAKB48だけでなくSKE48・NMB48の記事も扱います。', 'http://www.akb48rompen.com/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'AKB48まとめ物語', 'http://akbmonogatari.blog.jp/', NULL, 'http://akbmonogatari.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '話題ニュースまとめトレ速', 'http://blog.livedoor.jp/skybeta/', '話題ニュースまとめです。', 'http://blog.livedoor.jp/skybeta/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '注目！芸能情報', 'http://chu-mokugeinou.blog.jp/', '「注目！芸能情報」は芸能ニュース・芸能人・有名人の噂を紹介するブログです。 2chの芸能話題を『まとめ』てお届けしています。', 'http://chu-mokugeinou.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'NMB48まとめたやで！', 'http://nmbmarc2.doorblog.jp/', 'NMBまとめサイトです！', 'http://nmbmarc2.doorblog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'akb(ﾒ・ん・)？', 'http://akbakb0048.doorblog.jp/', 'AKB48Gのまとめサイトです', 'http://akbakb0048.doorblog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '芸能人ニュース速報', 'http://blog.livedoor.jp/sky_wing2010-geinou/', '芸能人のニュースを速報で伝えて行きます。', 'http://blog.livedoor.jp/sky_wing2010-geinou/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'エンタメちゃんねる', 'http://blog.livedoor.jp/ringotomomin/', '"今旬"を分かり易く。キュレーション。', 'http://blog.livedoor.jp/ringotomomin/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'main', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'AKB48速報', 'http://akb48sokuhou.doorblog.jp/', 'AKB48,SKE48,NMB48,SDN48ニュースの２ちゃんねるまとめブログだよ！', 'http://akb48sokuhou.doorblog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'チラ速 (*￣ω￣)/ -画像2chまとめブログ-', 'http://blog.livedoor.jp/nichmatomerunn/', '女性アイドル・AKB・芸能・面白ネタなどを中心に記事にしてます。', 'http://blog.livedoor.jp/nichmatomerunn/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, '執拗にAKB', 'http://akbmato.doorblog.jp/', 'AKB48,SKE48,NMB48に関する情報をまとめてお届けするブログです', 'http://akbmato.doorblog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'entry-content', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'AKB48地下速報', 'http://blog.livedoor.jp/akb48rhyh/', 'AKB48 SKE48 NMB48 HKT48 JKT48 乃木坂46まとめ', 'http://blog.livedoor.jp/akb48rhyh/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');


INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'AKB情報発信', 'http://yassakb.blog.jp/', 'ＡＫＢの最新情報を発信していきます', 'http://yassakb.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'Zにゅーす！～ももいろクローバー～', 'http://znews.blog.jp/', NULL, 'http://znews.blog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'SKE48まとめもらんだむ', 'http://ske48matomemo.doorblog.jp/', 'SKE48専用2ch.scまとめサイト', 'http://ske48matomemo.doorblog.jp/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');
INSERT INTO `alligate_2`.`Journal` (`id`, `name`, `siteurl`, `description`, `url`, `created`, `type`, `thumbnail`, `category`, `contentClass`, `itemClass`) VALUES (NULL, 'ぶらり(｀･ω･´)芸能', 'http://jhot.livedoor.biz/', '2ちゃんねるの芸能・モデルの面白記事を紹介', 'http://jhot.livedoor.biz/index.rdf', CURRENT_TIMESTAMP, 'rss', NULL, 'idol', 'article-body-inner', 't_h');

